name: CI/CD for Github Actions

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Package SpringBootDemo
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Verify JAR File
        run: ls -l target/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/springboot-githubactions.jar

  docker:
    name: Build & Push Docker Image
    needs: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar
          path: target/

      - name: Verify JAR File Exists
        run: ls -l target/

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/githubaction:latest

  deploy:
    name: Deploy to Server
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/githubaction:latest
            docker stop githubaction || true
            docker rm githubaction || true
            docker run -d --name githubaction -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/githubaction:latest
