name: CI/CD for Github actions

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Deploy SpringBootDemo
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Build with Maven
        run:  mvn clean package -DskipTests=false

      - name: Run Unit Tests
        run:  mvn test
